### ISSUE TITLE
Aws::S3::Errors::NoSuchKey: The specified key does not exist.

### ISSUE THREAD

**Issue by sakuro** [quipper/aya-issues#45381]
https://sentry.io/organizations/studysapuri/issues/2187660272/?referrer=github_plugin

```
Aws::S3::Errors::NoSuchKey: The specified key does not exist.
  vendor/quipper/schema/lib/schema/s3_manager.rb:43:in `download'
    io = object(key).get.body
  vendor/quipper/qmonolith/app/lib/qmonolith/portfolio/activity_note/activity_note_writer.rb:45:in `block in file_keys'
    meta[:file] = S3Manager.for(PrivateMedia).download(meta[:key])
  vendor/quipper/qmonolith/app/lib/qmonolith/portfolio/activity_note/activity_note_writer.rb:44:in `map'
    Array.wrap(files).compact.map do |meta|
  vendor/quipper/qmonolith/app/lib/qmonolith/portfolio/activity_note/activity_note_writer.rb:44:in `file_keys'
    Array.wrap(files).compact.map do |meta|
  vendor/quipper/qmonolith/app/lib/qmonolith/portfolio/activity_note/activity_note_writer.rb:8:in `initialize'
    @activity_note.image_keys = file_keys(images)
...
(168 additional frame(s) were not displayed)
```

**Comment by midwhite** [comment]
📝 
https://github.com/quipper/aya-issues/issues/42534#issuecomment-740354648

**Comment by midwhite** [comment]
- POST /activity_notes で新規作成した活動メモの情報を返す時に S3 側で no such key が返ってきている
- S3 側で PUT した瞬間に GET すると反映までにタイムラグがあってエラーが返ることがあると予想
- 非常に頻度も少なく、データ作成もできていてブラウザを更新すれば直るので close して良さそう
